<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_cuti_model extends CI_Model
{

    public $table = 'tbl_cuti';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('tbl_cuti.*, tbl_users.nama_lengkap');
		$this->db->join('tbl_users', 'tbl_users.id = tbl_cuti.users_id');
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
		$this->db->or_like('users_id', $q);
		$this->db->or_like('tanggal_mulai', $q);
		$this->db->or_like('tanggal_akhir', $q);
		$this->db->or_like('alasan', $q);
		$this->db->or_like('status', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

	function get_user_by_name_or_username($keyword) {
		$this->db->select('id, nama_lengkap, username');
		$this->db->like('nama_lengkap', $keyword);
		$this->db->or_like('username', $keyword);
		$this->db->limit(10);
		return $this->db->get('tbl_users')->result();
	}

	function get_by_tanggal_user_id($tanggal,$user_id){
		$query = $this->db->query("SELECT * FROM tbl_cuti WHERE tanggal = '$tanggal' AND users_id = '$user_id' AND (status = 'approved' OR status IS NULL)");
		// var_dump($query->result());
		return $query;
	}

}

/* End of file Tbl_cuti_model.php */
/* Location: ./application/models/Tbl_cuti_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-31 10:12:53 */
/* http://harviacode.com */
