<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_lapangan_model extends CI_Model
{

    public $table = 'tbl_lapangan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_lapangan', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('radius_diizinkan', $q);
	$this->db->or_like('jam_masuk_diizinkan', $q);
	$this->db->or_like('jam_keluar_diizinkan', $q);
	$this->db->or_like('petugas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
		$this->db->delete($this->table);
		if($this->db->error()['code'] != 0) {
			return $this->db->error()['message'];
		} else {
			return 'Delete Record Success';
		}
    }

	function get_users_assigned($id) {
		$this->db->select('*')->from('tbl_users')->where('id IN (SELECT id_users FROM tbl_penempatan_karyawan WHERE id_lapangan = '.$id.')');
		$query = $this->db->get();
		return $query->result();
	}

	function get_users_which_is_not_assigned($id) {
		$this->db->select('*')->from('tbl_users')->where('id NOT IN (SELECT id_users FROM tbl_penempatan_karyawan)');
		$query = $this->db->get();
		return $query->result();
	}

	function save_assigned_user($data) {
		$this->db->insert('tbl_penempatan_karyawan', $data);
	}

	function kosongkan_assigned_user($id) {
		$this->db->where('id_lapangan', $id);
		$this->db->delete('tbl_penempatan_karyawan');
	}

	function count_users_assigned($id) {
		$this->db->select('*')->from('tbl_users')->where('id IN (SELECT id_users FROM tbl_penempatan_karyawan)');
		$query = $this->db->get();
		return $query->num_rows();
	}

}

/* End of file Tbl_lapangan_model.php */
/* Location: ./application/models/Tbl_lapangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-01-27 01:03:48 */
/* http://harviacode.com */
